# Generated by Django 2.2.5 on 2019-09-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='VenueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(max_length=250)),
                ('address_line_3', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=250)),
                ('product_location', models.CharField(max_length=500)),
                ('toilet', models.BooleanField()),
                ('stock', models.BooleanField()),
                ('wheelchair_access', models.BooleanField()),
                ('opening_hours', models.BooleanField()),
                ('monday_open', models.TimeField()),
                ('monday_close', models.TimeField()),
                ('tuesday_open', models.TimeField()),
                ('tuesday_close', models.TimeField()),
                ('wednesday_open', models.TimeField()),
                ('wednesday_close', models.TimeField()),
                ('thursday_open', models.TimeField()),
                ('thursday_close', models.TimeField()),
                ('friday_open', models.TimeField()),
                ('friday_close', models.TimeField()),
                ('saturday_open', models.TimeField()),
                ('saturday_close', models.TimeField()),
                ('sunday_open', models.TimeField()),
                ('sunday_close', models.TimeField()),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.BusinessType')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.Contact')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.SocialMedia')),
                ('venue_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.VenueStatus')),
            ],
        ),
    ]
