# Generated by Django 2.2.5 on 2019-09-30 13:00
import datetime
from decimal import Decimal

import csv
from django.db import migrations


def import_csv_data(apps, schema_editor):
    # We can't import the models directly as they may be a newer
    # version than this migration expects. We use the historical versions.
    Venue = apps.get_model('venue', 'Venue')
    BusinessType = apps.get_model('venue', 'BusinessType')

    # Build a mapping between business type and description.
    business_type_description_lookup = {
        "Community Centre": "This business is a Community Centre",
        "Health Centre": "This business is a Health Centre",
        "Youth Club": "This business is a Youth Club",
        "Library": "This business is a Library",
        "GP": "This business is a GP",
        "Public Toilet": "This business is a Public Toilet",
        "Foodbank": "This business is a Foodbank",
        "Other": "This business is undefined"
    }

    # Build a mapping between business type and BusinessType objects.
    business_type_object_lookup = {}
    for label, description in business_type_description_lookup.items():
        business_type_object_lookup[label] = BusinessType(
            label=label, description=description)
        business_type_object_lookup[label].save()

    # Dictionary to hold unique social media objects.
    social_media_lookup = {}

    def try_date_from_string(string):
        parts = string.split(":")
        if len(string) > 0 and len(parts) == 2:
            try:
                return datetime.time(int(parts[0]), int(parts[1]))
            except ValueError:
                print("Error parsing string: ", string, " to int")
                return None
        else:
            return None

    with open('/code/server/venue/initial_venue_data.csv') as csv_file:
        csv_reader = csv.DictReader(csv_file, delimiter=',')

        for row in csv_reader:
            # Parse the opening times into datetime objects.
            opening_hours = row['OPENING_HOURS'] == 'True'
            if opening_hours:
            else:
                mon_open = None
                mon_close = None
                tue_open = None
                tue_close = None
                wed_open = None
                wed_close = None
                thu_open = None
                thu_close = None
                fri_open = None
                fri_close = None
                sat_open = None
                sat_close = None
                sun_open = None
                sun_close = None

            venue = Venue.ccreate()
            venue.name = row['NAME']
            venue.description = row['DESCRIPTION']
            venue.address_line_1 = row['ADDRESS1']
            venue.address_line_2 = row['ADDRESS2']
            venue.address_line_3 = row['ADDRESS3']
            venue.city = row['CITY']
            venue.postcode = row['POSTCODE']
            venue.country = row['COUNTRY']
            # venue.latitude=Decimal(row['LAT'])
            # venue.longitude=Decimal(row['LNG'])
            venue.phone = row['PHONE_PRIMARY']
            venue.email = row['EMAIL_PRIMARY']
            venue.website = row['WEBSITE']
            venue.twitter = row['TWITTER']
            venue.facebook = row['FACEBOOK']
            venue.product_location = row['PRODUCT_LOCATION']
            venue.business_type = business_type_object_lookup[row['BUSINESS_TYPE']]
            venue.toilet = row['TOILET'] == 'True'
            venue.wheelchair_access = row['WHEELCHAIR_ACCESS'] == 'True'
            venue.stock = row['STOCK'] == 'True'
            venue.opening_hours = opening_hours
            venue.monday_open = mon_open
            venue.monday_close = mon_close
            venue.tuesday_open = tue_open
            venue.tuesday_close = tue_close
            venue.wednesday_open = wed_open
            venue.wednesday_close = wed_close
            venue.thursday_open = thu_open
            venue.thursday_close = thu_close
            venue.friday_open = fri_open
            venue.friday_close = fri_close
            venue.saturday_open = sat_open
            venue.saturday_close = sat_close
            venue.sunday_open = sun_open
            venue.sunday_close = sun_close
            venue.save()


class Migration(migrations.Migration):
    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_csv_data)
    ]
